spring: 
  datasource:  
    url: jdbc:mysql://database-1.cj6squdbwvfi.ap-northeast-2.rds.amazonaws.com/myapp?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    generate-ddl: true